name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Build and tag Docker image
      run: |
        docker build -t mydemoimg .
    - name: run image
      run: |
        docker run -d -p 80:80 mydemoimg
